version: "3"
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    volumes:
      - mongodb:/data/db
      - mongoconfig:/data/configdb
    ports:
      - 27017:27017

  api:
    build: backend 
    container_name: api
    volumes:
      - .:/backend/code
    ports:
      - "8080:8080"
    extra_hosts:
      - "localhost:${EXTERNAL_IP}"
    links:
      - mongo
    depends_on:
      - mongo

  frontend:
    build: frontend 
    container_name: frontend
    expose:
      - 3000
    ports:
        - "3000:3000"
    volumes:
        - .:/frontend/app
    stdin_open: true

volumes:
  mongodb:
  mongoconfig:



