version: "3"
services:
  mongo:
    image: mongo:latest
    restart: always
    container_name: mongo
    volumes:
      - mongodb:/data/db
      - mongoconfig:/data/configdb
    ports:
      - 27017:27017

  web:
    build: backend
    volumes:
      - .:/backend/code
    ports:
      - "8080:8080"
    extra_hosts:
      - "localhost:${EXTERNAL_IP}"
    links:
      - mongo
    depends_on:
      - mongo

volumes:
  mongodb:
  mongoconfig:



